# Common Configuration
spring:
  profiles:
    active: "dev"

# Environment-specific configurations
---
spring:
  config:
    activate:
      on-profile: local
# Local environment specific properties go here

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_boot_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

---
spring:
  config:
    activate:
      on-profile: stg
# Staging environment specific properties go here

---
spring:
  config:
    activate:
      on-profile: prod
# Production environment specific properties go here
